# Generated by Django 5.2.14 on 2026-05-08 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acteurs', '0001_initial'),
        ('geo', '0001_initial'),
        ('projets', '0001_initial'),
        ('referentiels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppelOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.TextField()),
                ('lieu_execution', models.CharField(blank=True, max_length=250)),
                ('periode_publication', models.CharField(blank=True, max_length=50)),
                ('service_concerne', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('prevu', 'Prévu'), ('publie', 'Publié'), ('attribue', 'Attribué'), ('infructueux', 'Infructueux'), ('annule', 'Annulé')], default='prevu', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode_passation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referentiels.modepassation')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels_offres', to='projets.projet')),
            ],
            options={
                'verbose_name': "Appel d'Offres",
                'db_table': 'appels_offres',
            },
        ),
        migrations.CreateModel(
            name='Marche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_marche', models.CharField(max_length=100)),
                ('annee', models.SmallIntegerField()),
                ('objet', models.TextField()),
                ('montant_engage_dh', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('montant_marche_dh', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('montant_emis_dh', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('penalite_retard_dh', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('nb_jours_penalite', models.IntegerField(default=0)),
                ('superficie_potentielle', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('superficie_realisee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('superficie_travaillee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('superficie_plantee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('etat_avancement', models.CharField(choices=[('programme', 'Programmé'), ('en_cours', 'En cours'), ('suspendu', 'Suspendu'), ('resilie', 'Résilié'), ('receptionne', 'Réceptionné'), ('cede', 'Cédé'), ('cloture', 'Clôturé')], default='en_cours', max_length=50)),
                ('nb_beneficiaires', models.IntegerField(blank=True, null=True)),
                ('nb_beneficiaires_jeunes', models.IntegerField(blank=True, null=True)),
                ('nb_beneficiaires_femmes', models.IntegerField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistance_tech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acteurs.assistancetechnique')),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.commune')),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acteurs.entreprise')),
                ('mode_passation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referentiels.modepassation')),
                ('op', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acteurs.organisationprofessionnelle')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marches', to='projets.projet')),
            ],
            options={
                'verbose_name': 'Marché',
                'db_table': 'marches',
                'ordering': ['-annee', 'numero_marche'],
            },
        ),
        migrations.CreateModel(
            name='MarchePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dp', models.CharField(blank=True, max_length=20)),
                ('montant_dh', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='marches.marche')),
            ],
            options={
                'verbose_name': 'Paiement de Marché',
                'db_table': 'marche_paiements',
                'ordering': ['date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='MarchePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree_prevue_mois', models.SmallIntegerField(blank=True, null=True)),
                ('date_ods_notification', models.DateField(blank=True, null=True)),
                ('date_ods_commencement', models.DateField(blank=True, null=True)),
                ('date_ods_commencement_reel', models.DateField(blank=True, null=True)),
                ('date_ordre_arret', models.DateField(blank=True, null=True)),
                ('date_ordre_reprise', models.DateField(blank=True, null=True)),
                ('date_reception_prevue', models.DateField(blank=True, null=True)),
                ('date_reception_reelle', models.DateField(blank=True, null=True)),
                ('superficie_travaillee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('superficie_plantee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montant_emis_dh', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('observations', models.TextField(blank=True)),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='marches.marche')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referentiels.phase')),
            ],
            options={
                'verbose_name': 'Phase de Marché',
                'db_table': 'marche_phases',
            },
        ),
        migrations.CreateModel(
            name='MarchesBeneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie_cedee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_cession', models.DateField(blank=True, null=True)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acteurs.beneficiaire')),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaires_marche', to='marches.marche')),
            ],
            options={
                'verbose_name': 'Bénéficiaire du Marché',
                'db_table': 'marche_beneficiaires',
                'unique_together': {('marche', 'beneficiaire')},
            },
        ),
    ]
