# Generated by Django 5.2.14 on 2026-05-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('arboriculture', 'Arboriculture'), ('elevage', 'Élevage'), ('apiculture', 'Apiculture'), ('plantes_aromatiques', 'Plantes Aromatiques'), ('irrigation', 'Irrigation'), ('autre', 'Autre')], max_length=50)),
            ],
            options={
                'verbose_name': 'Filière',
                'db_table': 'filieres',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='ModePassation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Mode de Passation',
                'db_table': 'modes_passation',
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('ordre', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Phase',
                'db_table': 'phases',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='StatutProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Statut Projet',
                'db_table': 'statuts_projet',
            },
        ),
    ]
