# Generated by Django 5.2.14 on 2026-05-08 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=200)),
                ('contact_nom', models.CharField(blank=True, max_length=150)),
                ('contact_tel', models.CharField(blank=True, max_length=50)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assistance Technique',
                'db_table': 'assistances_techniques',
                'ordering': ['raison_sociale'],
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=200)),
                ('contact_nom', models.CharField(blank=True, max_length=150)),
                ('contact_tel', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.CharField(blank=True, max_length=150)),
                ('adresse', models.TextField(blank=True)),
                ('ice', models.CharField(blank=True, max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'db_table': 'entreprises',
                'ordering': ['raison_sociale'],
            },
        ),
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('nom_complet', models.CharField(max_length=200)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('douar', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.commune')),
            ],
            options={
                'verbose_name': 'Bénéficiaire',
                'db_table': 'beneficiaires',
                'ordering': ['nom_complet'],
            },
        ),
        migrations.CreateModel(
            name='OrganisationProfessionnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('type_op', models.CharField(choices=[('cooperative', 'Coopérative'), ('association', 'Association'), ('gie', 'GIE'), ('autre', 'Autre')], default='cooperative', max_length=30)),
                ('contact_nom', models.CharField(blank=True, max_length=150)),
                ('contact_tel', models.CharField(blank=True, max_length=50)),
                ('nbre_adherents', models.IntegerField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.commune')),
            ],
            options={
                'verbose_name': 'Organisation Professionnelle',
                'verbose_name_plural': 'Organisations Professionnelles',
                'db_table': 'organisations_professionnelles',
                'ordering': ['nom'],
            },
        ),
    ]
