# Generated by Django 5.2.14 on 2026-05-08 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cercle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cercle',
                'db_table': 'cercles',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('region', models.CharField(default='Marrakech-Safi', max_length=100)),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
                'db_table': 'provinces',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
                ('type_commune', models.CharField(choices=[('CT', 'Chef-lieu'), ('CR', 'Commune Rurale'), ('CU', 'Commune Urbaine')], default='CT', max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('cercle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communes', to='geo.cercle')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communes', to='geo.province')),
            ],
            options={
                'verbose_name': 'Commune',
                'db_table': 'communes',
                'ordering': ['libelle'],
            },
        ),
        migrations.AddField(
            model_name='cercle',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cercles', to='geo.province'),
        ),
        migrations.AlterUniqueTogether(
            name='cercle',
            unique_together={('province', 'libelle')},
        ),
    ]
