# Generated by Django 5.2.14 on 2026-05-08 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('referentiels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=400)),
                ('date_demarrage', models.DateField(blank=True, null=True)),
                ('duree_annees', models.SmallIntegerField(blank=True, null=True)),
                ('superficie_programmee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cout_global_kdh', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('nbre_benef_potentiel', models.IntegerField(blank=True, null=True)),
                ('unites_valorisation', models.SmallIntegerField(default=0)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projets', to='referentiels.filiere')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.province')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projets', to='referentiels.statutprojet')),
            ],
            options={
                'verbose_name': 'Projet',
                'db_table': 'projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjetProgrammation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.SmallIntegerField()),
                ('superficie_programmee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('superficie_realisee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_programme_kdh', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('budget_engage_kdh', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('observations', models.TextField(blank=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmations', to='projets.projet')),
            ],
            options={
                'verbose_name': 'Programmation Annuelle',
                'db_table': 'projets_programmation',
                'ordering': ['annee'],
                'unique_together': {('projet', 'annee')},
            },
        ),
    ]
